#!/bin/bash

# Set default values
warninglevel='0.5'
criticallevel='0.8'

while getopts hw:c: opt; do
  case $opt in
    w)
      warninglevel=$OPTARG
      ;;
    c)
      criticallevel=$OPTARG
      ;;
    h)
      echo "Checks the cpu load of a server"
      echo "Usage ssh_cpu.sh [-w] [-c] [-h]"
      echo "    -w set the load level considered a warning"
      echo "    -c set the load level considered critical"
      echo "    -h display this help text"
      exit 3
      ;;
    \?)
      echo "Usage ssh_cpu.sh [-w] [-c]"
      exit 3
      ;;
  esac
done

commandoutput=`uptime`

commandoutputarray=($commandoutput)
commandoutputarraylength=${#commandoutputarray[@]}

one=${commandoutputarray[`expr $commandoutputarraylength - 3`]}
one="${one//,}"
five=${commandoutputarray[`expr $commandoutputarraylength - 2`]}
five="${five//,}"
fifteen=${commandoutputarray[`expr $commandoutputarraylength - 1`]}

if [ $(bc <<< "$criticallevel <= $one") -eq 1 ]; then
  echo "CPU CRITICAL - CPU load greater than threshold $one"
  exit 2
elif [ $(bc <<< "$warninglevel <= $one") -eq 1 ]; then
  echo "CPU WARNING - CPU load greater than threshold $one"
  exit 1
else
  echo "CPU OK - Load is $one"
  exit 0
fi